import { Inter, Yaldevi } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div>
          {children}
        </div>
        <footer className="text-xl text-center p-5 mx-20 my-2 bg-orange-500 rounded-xl">
          This is my next js app
        </footer>
      </body>
    </html>
  );
}
